### PR TITLE
Update setup.py

### PR DESCRIPTION
**Pull request by rkannan87**
Updated the latest SIP build version

### CODE REVIEW

**Comment by ayushpriya10** [comment]
Hey @rkannan87 thanks for the PR! I'd like to know a couple things:

- Is there a necessity to upgrade the module version?
- Have you tested all functionality present in the application with the upgraded module?

**Comment by rkannan87** [comment]
Hey Ayush thanks for the reply I have update only the version of the sip-build  to run the pipgui package because it was outdated

**Comment by ayushpriya10** [comment]
@rkannan87 I understand that an update to the module is available but the reason I asked you the question is that just the availability of an updated module is not reason enough to modify a stable application. Because of this reason I asked you the second question about whether you have tested all functionalities with the updated module version to identify if it breaks anything.

**Comment by L04DB4L4NC3R** [comment]
@ayushpriya10 @rkannan87  this PR is going stale. Will close it in a couple of days if not needed

**Pull request closed without merging**
